### ISSUE TITLE
Text field with autocompletion of another text field: "keine Auswahl" should not be saved

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#100]
Currently, when I have a field of type text, that is linked with another field and I do not select anything, the string "keine Auswahl" ist saved. Correct should be to not save anything or an empty string.

![Screenshot_2020-02-20 Datalynx Grid Page 1](https://user-images.githubusercontent.com/1620975/74919008-3e2f2e00-53ca-11ea-90e0-caf60fde0660.png)

So If "keine Auswahl" is selected, then this should be stripped in validation....

**Comment by michaelpollak** [comment]
Can't reproduce this behaviour (yet).
I set up a new dl instance,
added field tms and field text,
added fieldgroup with both.

When I add text it works, when I leave text blank it remains an empty string. The string "keine Auswahl" is also not to be found in the codebase, any chance this was just input and thus is stored correct? Thank you for clarifying David,
mfg

**Comment by dasistwas** [comment]
Yes, the problem disappeared. I think due to a change we made: We replaced the "Auswahl" with "Keine Auswahl". Because right now you can select "Auswahl" which is in reality "Keine Auswahl". 

So we should solve instead the problem how to make "No choice". Because Moodle does not provide a "delete" button for an already made choice. So the only choice is to provide a choice for "no choice". OMG! why is Moodle so ..... (choice of slurs omitted)
