### ISSUE TITLE
Custom filter: for multiselect fields add feature to change between AND/OR within the field

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#102]
Following changes:

# Custom filter settings

For multiselect (multiselect, teammember) add an option to enable the selection of "AND/OR" in the Custom filter in the view.

# Custom filter in the view

When the custom filter is displayed, then there should be a dropdown right of the filter options of the (multi)select field with 2 choices, default is first:
- "All selected options have to be part of the entry"
- "One of the selected options has to be part of the entry"

If you find a nicer English wording, you are welcome to modify ;-)

**Comment by michaelpollak** [comment]
I assume I understand what you are refering to,
will add a checkbox in the field config to select if all values have to be selected (and) or only one of the searched values needs to be present (or).

**Comment by dasistwas** [comment]
@michaelpollak Sorry I did forget to add description. Added it right now.

**Comment by michaelpollak** [comment]
Thank you David :+1:

**Comment by dasistwas** [comment]
With single select it makes no sense so only for multi select

**Comment by michaelpollak** [comment]
Modified it a bit as to me a checkbox looks cleaner for an either/or option.
We could implement it for teammembers too?

Help button is not yet showing up, it says the field is not found. Is it clear enough or do we need more explanation there? Thank you for your feedback!

**Comment by dasistwas** [comment]
Yes, thank you
