### ISSUE TITLE
The pdf view does not work in moodle 3.8.

### ISSUE THREAD

**Issue by jesusman111** [dasistwas/moodle-mod_datalynx#104]
The pdf view does not work in moodle 3.8.
When you try to use it, the screen goes blank.

**Comment by dasistwas** [comment]
Hi @jesusman111 
I just released a version compatible with Moodle 3.8 on moodle.org.
Enjoy!
Kind regards,
David

**Comment by jesusman111** [comment]
Thanks a lot
This is wonderfull!!!
