### ISSUE TITLE
Error "quicksearch" and filter

### ISSUE THREAD

**Issue by jesusman111** [dasistwas/moodle-mod_datalynx#106]
When a filter is used in which a type selector field is included, doing a quick search with "quicksearch" fails.

It shows "Error reading from database"

Regards

**Comment by dasistwas** [comment]
Hi,
thank you for the bug report. Could you provide some screenshots and clarify what a "type selector" field is? Or providing a download link of a backup of your datalynx instance or your course would be even better. 
Thank you,
David

**Comment by jesusman111** [comment]
Hi:

When I use a filter in which the field "student name" is not used, the
quick search works correctly.

[image: cap-2.png]
[image: cap-5.png]

[image: cap-6.png]
When I use a filter in which the field "student's name" is used, the quick
search works correctly.
[image: cap-1.png]
[image: cap-3.png]

[image: cap-4.png]
Thanks for everything

**Comment by jesusman111** [comment]
![cap-6](https://user-images.githubusercontent.com/61394948/75465209-96e16680-5988-11ea-8033-2747c2be9858.png)
![cap-5](https://user-images.githubusercontent.com/61394948/75465213-98129380-5988-11ea-807c-19ecf5a4c1de.png)
![cap-4](https://user-images.githubusercontent.com/61394948/75465214-98129380-5988-11ea-85d2-23a4f5d0f241.png)
![cap-3](https://user-images.githubusercontent.com/61394948/75465216-98ab2a00-5988-11ea-91c2-3062a5193003.png)
![cap-2](https://user-images.githubusercontent.com/61394948/75465217-9943c080-5988-11ea-9afa-ace59954df7d.png)
![cap-1](https://user-images.githubusercontent.com/61394948/75465221-99dc5700-5988-11ea-9a25-ce4fd8fc642d.png)

**Comment by michaelpollak** [comment]
I tried to reproduce the error without success (which I guess is a success...)
Can you @jesusman111 post a backup of your course for evaluation? What moodle version are you working with?

So what I did is:
- Set up a new instance
- Added a field of type and text and a field of type select
- Added a filter to mimic your settings.

Quicksearch in combination with the filter works as expected. Thank you for your clarification!

**Comment by jesusman111** [comment]
Hi,
I am using moodle 3.8
In the select field, "Nombre del alumno" I have a very large list of names.
Is it possible that the large amount of data causes the error?

Thank you so much
Warm regards

**Comment by jesusman111** [comment]
I attach the backup you ask me

[copia_de_seguridad-moodle2-activity-300-datalynx300-20200304-2126.zip](https://github.com/dasistwas/moodle-mod_datalynx/files/4289531/copia_de_seguridad-moodle2-activity-300-datalynx300-20200304-2126.zip)

**Comment by jesusman111** [comment]
Do you know if there is updated documentation of this plugins?
Thank you
Kind regards

**Comment by jesusman111** [comment]
Hello again
It seems that the fault occurs when in the filter configuration menu, nothing is entered in the search field.
Regards

**Comment by michaelpollak** [comment]
Thank you, I have restored your course backup and did some tests.
We join multiple version of mdl_datalynx_fields which breaks the database request. In my tests this only occurs when I sort by "Curso y grupo", so as a quick fix you can remove this sort parameter and check sort parameters individually. Will figure out what the culprit is and push a fix asap. Thanks for the report.

```
LEFT JOIN mdl_groups g ON g.id = e.groupid JOIN mdl_datalynx_contents cs ON cs.entryid = e.id JOIN mdl_datalynx_fields f ON cs.fieldid = f.id LEFT JOIN mdl_datalynx_contents c6
ON (c6.entryid = e.id AND c6.fieldid = ?) LEFT JOIN mdl_datalynx_fields f ON c6.fieldid = f.id LEFT JOIN
```

**Comment by michaelpollak** [comment]
Looks good, tested with mdl35 and 38 :)

**Comment by jesusman111** [comment]
I don't understand the problem well, but if I can help in any way at the user level, please tell me.
Thanks for everything.

**Comment by michaelpollak** [comment]
It's solved now, thank you for the report. It will be fixed for you with the next automatic update of datalynx :)
Have a nice weekend.

**Comment by jesusman111** [comment]
Magnificent!
Could you download it to prove it?
Thank you very much again

**Comment by michaelpollak** [comment]
If I understand you right you are asking me to test with your course backup?
I did exactly that, tested with your course backup, and with the update I programmed your setup works fine. The filter plus quicksearch causes no problems anymore. 

You can also test yourself, but that depends on your IT knowledge. Easiest way is to wait for David to approve and have moodle install the update for you. If I did misunderstand you please let me know :)

**Comment by jesusman111** [comment]
I thought there was a beta version that I could try, but if there isn't one I will wait for it to come out.
Thank you

**Comment by dasistwas** [comment]
I still get an error:
```
Debug info: Unknown column 'f.id' in 'where clause'
SELECT COUNT(e.id) FROM mdl_datalynx_entries e
JOIN mdl_user u ON u.id = e.userid
LEFT JOIN mdl_groups g ON g.id = e.groupid JOIN mdl_datalynx_contents cs ON cs.entryid = e.id JOIN mdl_datalynx_fields fsimple ON cs.fieldid = fsimple.id LEFT JOIN
(SELECT r.itemid, r.component, r.ratingarea, r.contextid,
COUNT(r.rating) AS numratings,
AVG(r.rating) AS avgratings,
SUM(r.rating) AS sumratings,
MAX(r.rating) AS maxratings,
MIN(r.rating) AS minratings,
ur.id as ratingid, ur.userid as ratinguserid, ur.scaleid, ur.rating AS usersrating
FROM mdl_rating r
LEFT JOIN mdl_rating ur ON ur.contextid = r.contextid
AND ur.itemid = r.itemid
AND ur.component = r.component
AND ur.ratingarea = r.ratingarea
AND ur.userid = ?
WHERE r.contextid = ?
AND r.component = ?
AND r.ratingarea = ?
GROUP BY r.itemid, r.component, r.ratingarea, r.contextid, ratingid, ur.userid, ur.scaleid
ORDER BY r.itemid) AS er ON er.itemid = e.id WHERE e.dataid = ? AND ( (cs.content LIKE ? ESCAPE '\\' OR u.firstname LIKE ? ESCAPE '\\' OR u.lastname LIKE ? ESCAPE '\\' OR u.username LIKE ? ESCAPE '\\' OR (cs.content LIKE ? ESCAPE '\\' AND f.id = ?)) )
[array (
0 => '2',
1 => 13471,
2 => 'mod_datalynx',
3 => 'entry',
4 => '6',
5 => '%A%',
6 => '%A%',
7 => '%A%',
8 => '%A%',
9 => '%#1%#',
10 => '144',
)]
Error code: dmlreadexception 
```
