### ISSUE TITLE
Pdf frame error (pdf view). 

### ISSUE THREAD

**Issue by jesusman111** [dasistwas/moodle-mod_datalynx#107]
In the pdf view, when you try to put an image with pdf frame on all pages, it is only shown in the first one, even if it is indicated that they are included in all of them.

Regards

**Comment by jesusman111** [comment]
Attached is a pdf document in which you can see that the watermark and the "pdf frame" image only appears on the first page.
Regards
[watermark-frame.pdf](https://github.com/dasistwas/moodle-mod_datalynx/files/4356469/watermark-frame.pdf)

**Comment by michaelpollak** [comment]
I feel like this is a documentation error too, thank you for bringing it up! If you want to see watermarks or frames on every page you can select to break the page after every entry.

- Go to your pdf view settings,
- open "PDF Margins and paging", 
- change "Page break" to "Entry".

If you re-export your pdf you will see a watermark on every page (except the attachments).
Does this help your usecase or do you need different functionality?

**Comment by jesusman111** [comment]
With the watermark it works for me but with the frame it doesn't.
With the pdf frame it only appears on the first page, although on each page there is only one entry.
Thank you very much for the clarification

**Comment by michaelpollak** [comment]
You are absolutely right, I have patched this already and it will be available for you with the next update.

**Comment by jesusman111** [comment]
I attach an example so you can see it
[ejemplo.pdf](https://github.com/dasistwas/moodle-mod_datalynx/files/4369610/ejemplo.pdf)

**Comment by michaelpollak** [comment]
I was able to reproduce and fix this bug :)

**Comment by jesusman111** [comment]
Magnificent!
Another corrected
Thank you
