### ISSUE TITLE
Filter error, option per page

### ISSUE THREAD

**Issue by jesusman111** [dasistwas/moodle-mod_datalynx#108]
When a filter is defined, the option to select a number of entries per page does not work when applying that filter.
Regards

**Comment by jesusman111** [comment]
It seems to happen is this option is not saved in the filter.
Regards

**Comment by jesusman111** [comment]
I attach a backup copy of a case in which it occurs
[copia_de_seguridad-moodle2-activity-300-datalynx300-20200304-2126.zip](https://github.com/dasistwas/moodle-mod_datalynx/files/4289553/copia_de_seguridad-moodle2-activity-300-datalynx300-20200304-2126.zip)

**Comment by jesusman111** [comment]
My version of moodle is 3.8 and that of datalynx is on 27/02/2020

**Comment by jesusman111** [comment]
Attached are screenshots showing that the filter per page option does not work.
![cap-7](https://user-images.githubusercontent.com/61394948/77047167-9a36a380-69c4-11ea-953d-648fa45824b1.png)
![cap-8](https://user-images.githubusercontent.com/61394948/77047177-9c98fd80-69c4-11ea-946c-0bce1edc8fd1.png)

**Comment by michaelpollak** [comment]
Thank you for your report, this bug has been fixed and will be gone with the next release.
Great job adding screenshots and a backup, it was easy to follow and reproduce.

**Comment by jesusman111** [comment]
Magnificent!
Thank you very much again

**Comment by dasistwas** [comment]
Great fix, thank you
