### ISSUE TITLE
Field label

### ISSUE THREAD

**Issue by jesusman111** [dasistwas/moodle-mod_datalynx#109]
I have tried using [[fieldname @]] in moodle 3.8 and I have not got it to work. It simply shows "[[fieldname @]]"

Kind regards

**Comment by dasistwas** [comment]
You have to write [[fieldname]]@

**Comment by jesusman111** [comment]
OK.
Thank you
Kind regards

**Comment by jesusman111** [comment]
But I don't understand the difference between using [[fieldname]] and [[fieldname]]@
Could you tell me which one it is?, please.
Thanks again

**Comment by dasistwas** [comment]
You user [[fieldname]]@ for example in an HTML element like that:
`<div class="[[fieldname]]@"></div>`
If you do not use it like that, the Editor will destroy your source code. Not very proud of the solution. It's more an ugly hack.

**Comment by jesusman111** [comment]
Ok
Thank you again
