### ISSUE TITLE
Configurable filter order

### ISSUE THREAD

**Issue by jesusman111** [dasistwas/moodle-mod_datalynx#111]
Could the order of appearance of the filters be made configurable?
Thank you

**Comment by michaelpollak** [comment]
It's simply sorted by the id which basically means by the order the filters were added. 
I don't know that an option to custom sort it would be useful to many. Maybe ordering it by name alphabetically could suffice, so you can name your filters "A-filter" and "B-filter" but this also makes a bit of coding necessary.

Is there any usecase you come across that makes this feature important? Maybe we find other users interested and can fund the development, as suggested by David.

**Comment by jesusman111** [comment]
It is not something too important, but it can be useful when there are many filters defined and you want to introduce a new one in a certain order.
a cordial greeting

**Comment by dasistwas** [comment]
@jesusman111 not sure, but the custom filter already offers sorting.  Maybe I don't understand the requirement....

**Comment by jesusman111** [comment]
I have not got the custom filters to work. I may not know how to use them or there may be some failure.
Is there any place where its operation is detailed to be able to do tests?
Thank you

**Comment by jesusman111** [comment]
The idea is that the filters can appear in the order that the user wants.
I attach a montage that I have made.
Thanks for your great work
![cap-15](https://user-images.githubusercontent.com/61394948/77096343-83696e80-6a0f-11ea-944f-fee937a3d683.png)

**Comment by michaelpollak** [comment]
How about we change the order filters are displayed to alphabetical? So you could simply (re)name your filters accordingly, (2 - filter one, 1 - filter two) and they are displayed in this order. 
Your proposed solution takes up a lot of development assets, it's a neat idea but the development efforts are disproportional.

**Comment by jesusman111** [comment]
Wonderful idea
Thank you

**Comment by michaelpollak** [comment]
Pending Davids approval filters now are always displayed in alphabetical order by name. This makes your feature request possible but does not disturb any other usecases. Should be out with the next release. Thanks for the proposal!

**Comment by jesusman111** [comment]
Perfect!
Thank you

**Comment by dasistwas** [comment]
Great and efficient solution. Thank you.
