### ISSUE TITLE
Errors in the csv view configuration

### ISSUE THREAD

**Issue by jesusman111** [dasistwas/moodle-mod_datalynx#113]
I have detected two small errors in the csv view configuration:
The first is that when the field label is selected it is not automatically included in the list of fields to export.
The second is that when a date type field [[Date]] is exported to excel, in Excel it is received with universal unix date format.
I use moodle 3.8
Regards

**Comment by jesusman111** [comment]
Attached are screenshots showing that dates are exported to unix format.

![CAP-100](https://user-images.githubusercontent.com/61394948/77368589-d703f100-6d5c-11ea-80c4-17e10c2961d1.png)
![CAP-102](https://user-images.githubusercontent.com/61394948/77368594-d9fee180-6d5c-11ea-82cd-24990b01b276.png)

**Comment by michaelpollak** [comment]
I'd argue this makes sense as a timestamp can be displayed and converted in a variety of ways. What would you prefer? Having the date as a string makes it much harder to work with in software and database tools.

**Comment by jesusman111** [comment]
I thought it could be shown as follows: "dd / mm / yyyy", but it could also remain as it is.
Regars

**Comment by dasistwas** [comment]
I think you have the settings in the field so you can choose how dates are displayed.

**Comment by dasistwas** [comment]
There are also some hidden tricks like [datefield:timestamp] to export as timestamp

**Comment by michaelpollak** [comment]
I've tested his report, he is right. 
The field class "time" has not been updated and is buggy. I agree, exporting the time to the csv file like it is displayed in the view - and with the formating options added to the settings makes sense.

**Comment by jesusman111** [comment]
Ok.
Thanks you

**Comment by michaelpollak** [comment]
For reference, this is the code:
https://github.com/michaelpollak/moodle-mod_datalynx/blob/9a83df243e48661a9c6b9a45fc806172bf561265/field/time/renderer.php#L76

**Comment by jesusman111** [comment]
Ok.
Thanks you

**Comment by michaelpollak** [comment]
@dasistwas I am not sure how you want to handle this, we implemented forced timestamp export a few years ago, to me it seams that exporting the user selected format makes more sense. Thus I pushed a commit to do exactly that, let me know if this is how you want the code to work or if forced timestamps are better.
Thank you :)

**Comment by dasistwas** [comment]
I think that's a good solution.
