### ISSUE TITLE
#export: all and #export: page

### ISSUE THREAD

**Issue by jesusman111** [dasistwas/moodle-mod_datalynx#114]
In pdf view, #export: all and #export: page work exactly the same.
I use moodle 3.8
Regards

**Comment by michaelpollak** [comment]
Tested this and disagree. Maybe the usage is not clear enough?

Export Page is useful if you have a long list of entries and only show e.g. two per page. If you want to see entry 3 and 4 you go to the second page of this instance. And if you now click "Export Page" you will get a pdf with entry 3 and 4, excluding all other entries. In the same situation if you select "Export all" you get a pdf withe all entries 1 - n.

Hope this helps, if so we can close this issue :) Thank you for the report, hopefully we can write an updated documentation in the future to clarify usage.

**Comment by michaelpollak** [comment]
PS.: Confirmed with mdl 35 and 38 :)

**Comment by jesusman111** [comment]
Do you need any further clarification?
I am at your service

**Comment by michaelpollak** [comment]
Do you understand my explanation? :) 
Export Page should work like that with your moodle as well, if you can test and confirm I'd be happy.

**Comment by jesusman111** [comment]
Simply, what I don't understand is the difference between the option to export page and export everything, since it works the same for me.
Thanks for everything

**Comment by michaelpollak** [comment]
Export page just exports the page you are currently seeing to a pdf document,
while Export all outputs everything in this instance regardless of the page you are currently looking at.

It works the same if you only have a single page, but if you choose to only show one entry per page you see a page selector and can choose what page will be exported. Is this clearer?

**Comment by jesusman111** [comment]
OK. I understand now.
Thank you very much for the aclarations

**Comment by michaelpollak** [comment]
Great :) Glad to help, I'll close this issue now. Have a good day.
