### ISSUE TITLE
Permits and new roles

### ISSUE THREAD

**Issue by jesusman111** [dasistwas/moodle-mod_datalynx#119]
Is it possible that the viewing and editing permissions could include the new roles created and not only the natives of moodle?
Thanks for everything

**Comment by michaelpollak** [comment]
Hello there :)
In theory yes but we would need to extend that feature in the codebase. Could you explain the usecases you see for it? Maybe we can simplify from "all roles", the interface gets cluttered pretty quickly. 

Thanks for your feedback.

**Comment by jesusman111** [comment]
Hello Michael:
I give you some examples:
- Sometimes there are fields that are interesting to show some teachers and / or students and others not.
- The same goes for editing fields, views or filters. If there are more roles, differentiated permissions can be given.
- Another case is when notifications are sent. If more roles can be delimited more to those who are notified.

I don't know if it would be better to use moodle groups instead of roles?

Thank you again.

**Comment by dasistwas** [comment]
Hi,
in fact the wording is wrong in the settings: These are not roles but permissions. So you can add the permissions to any roles. The fix would be to adjust the language strings.
Kind regards,
David

**Comment by jesusman111** [comment]
Hello David:
I do not understand what you are saying.
Could you explain a little more?

Thank you very much

**Comment by dasistwas** [comment]
When you go to Manage -> Edit View then you have the form with the view settings. On top of the form you have the setting "Visible to": Then you have these choices:

- manager
- teacher
- student
- guest

But these choices are labelled the wrong way. They should have the following label:
- Users with the view privilege "manager" usually assigned to managers
- Users with the view privilege "teacher" usually assigned to teachers
- Users with the view privilege "student" usually assigned to students
- Users with the view privilege "guest" usually assigned to guests or authenticated users

So speaking in Moodle terms, you have got permissions or capabilities that are by default assigned to a role. But these permission can be used for other roles as well.

When you go to a datalynx activity and then open the permissions you will find these permissions there and can adapt them. Here are two examples:

### Guest view access privilege
mod/datalynx:viewprivilegeguest

### Manager view access privilege
mod/datalynx:viewprivilegemanager

**Comment by jesusman111** [comment]
I understand then that there can be as many possible items as there are different permissions.
Is this correct?
Thanks for the clarification

**Comment by dasistwas** [comment]
You can assign these 4 priviliges to any role. You  can also use the same permission for different roles at the same time. So basically you 4 permissions to control the access. I never needed more than that and I consider myself as heavy user of the module ;-).

**Comment by jesusman111** [comment]
In general, with four types it is fine, but for the subject of notifications it is different.
You can many different groups than you want to send notifications to.
It can also happen that there are certain fields that can be visible or editable more than four different groups.

Datalynx is a great application and allows many different uses. So there may be situations where this is necessary.
Thank you so much for everything

**Comment by dasistwas** [comment]
Yes there is always something to improve, I agree. There are already quite some possibilities to control notifications, but it is possible to add further possibilities. 
I think we have clarified this issue and I am closing it.

**Comment by jesusman111** [comment]
Thanks you
