### ISSUE TITLE
Restore teammemberselect removes quotes

### ISSUE THREAD

**Issue by michaelpollak** [dasistwas/moodle-mod_datalynx#13]
When I restore a teammemberselect field the content is inserted without quotation marks.
The quotation marks are present in the backup file.

Correct format: ["123"], ["123","234"]
Restored: [123], [123,234]

**Comment by dasistwas** [comment]
Does this problem really exist?

**Comment by michaelpollak** [comment]
Seems this was some fluke incident, will close this.
