### ISSUE TITLE
mod_datalynx_mod_form::definition() calls add_action_buttons() twice

### ISSUE THREAD

**Issue by mudrd8mz** [dasistwas/moodle-mod_datalynx#15]
This might have been intended as a feature, trying to avoid unnecessary scrolling. However, the consistency is a key element of usability. It does not work well if all activity modules work certain way, and only this would would be different.

The `add_action_buttons()` should be called just once at the end, same as elsewhere.

**Comment by michaelpollak** [comment]
Thank you for your feedback David,
you are right, the intention was to avoid scrolling and the critique is valid. We will change this in the next minor release to allow for a streamlined UI experience.
