### ISSUE TITLE
Setting form fields without a help tooltip

### ISSUE THREAD

**Issue by mudrd8mz** [dasistwas/moodle-mod_datalynx#16]
Certain fields in the setting form are not fully intuitive purely from their label text. E.g. "Interval duration" or "Number of intervals". There should be a help tool-tip describing them.

**Comment by mudrd8mz** [comment]
Same applies for other fields like "Maximum entries" where -1 seems to have a special meaning.

**Comment by michaelpollak** [comment]
Thanks for your feedback, changes are committed and will be added to the next minor release.
