### ISSUE TITLE
It is unclear how this relates to mod_dataform

### ISSUE THREAD

**Issue by mudrd8mz** [dasistwas/moodle-mod_datalynx#17]
It is apparent that the module re-uses significant parts of the existing mod_dataform plugin. It even tries to handle its content files via the pluginfile callback. However, I haven't found any clarification of what makes this module unique, why it has been forked (instead of contributing to the original one), what are made differences etc.
Also, copyright notices are not clear on this, kept with Itamar Tzadok's copyright. Please refer to https://docs.moodle.org/dev/Plugin_contribution_checklist#Copyrights

**Comment by mudrd8mz** [comment]
Another example of this confusion is when original code was left in place, with the "Dataform" search & replaced with "Datalynx" so it now reads like:
```
 *          The Datalynx has been developed as an enhanced counterpart
 *          of Moodle's Database activity module (1.9.11+ (20110323)).
 *          To the extent that Datalynx code corresponds to Database code,
 *          certain copyrights on the Database module may obtain.
```

**Comment by dasistwas** [comment]
Hi David,

I just changed the copyright attribution according to the moodle docs recommendation as good as I could. You can see the changes in e747e144e45e2d8684a81dca7adb314f905c2e30 
I would be happy if you could give me feedback if that solves this issue or if further work is necessary. 

Kind regards,
David

**Comment by mudrd8mz** [comment]
This change looks good to me, thanks for it! Can you please release a new version in the Moodle Plugins directory with these changes included?

**Comment by dasistwas** [comment]
Release is done quite a while ago. So closing this issue.
