### ISSUE TITLE
Line id is used twice which leads to corrupt HTML output

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#22]
When I use 2 fieldgroups in a view I have the same ID twice. Using ids should always be done with care and if possible then use classes instead:

`<div class="lines" id="line_1">`
Just discovered, that there is more HTML mess. Please be careful:
`        <div class="form-control-feedback invalid-feedback" id="id_error_" >`

**Comment by dasistwas** [comment]
... there are a lot more problems with ids....

**Comment by dasistwas** [comment]
also with attribute size...

**Comment by michaelpollak** [comment]
Thank you for your feedback, I have not expected multiple fieldgroups to be added to one view. Fixed the JS by using data-line and more precise selectors but this leads to other complications with the validation.

**Comment by dasistwas** [comment]
Duplicate issue. Closing.
