### ISSUE TITLE
After adding a site badge, warning is displayed concerning missing capability

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#23]
Capability "mod/datalynx:notifymemberupdated" was not found! This has to be fixed in code.

    line 453 of /lib/accesslib.php: call to debugging()
    line 578 of /lib/messagelib.php: call to has_capability()
    line 187 of /lib/messagelib.php: call to message_get_providers_for_user()
    line 1001 of /lib/badgeslib.php: call to message_send()
    line 486 of /lib/badgeslib.php: call to badges_notify_badge_award()
    line 558 of /lib/badgeslib.php: call to badge->issue()
    line 95 of /badges/action.php: call to badge->review_all_criteria()

Capability "mod/datalynx:notifymemberupdated" was not found! This has to be fixed in code.

    line 453 of /lib/accesslib.php: call to debugging()
    line 578 of /lib/messagelib.php: call to has_capability()
    line 187 of /lib/messagelib.php: call to message_get_providers_for_user()
    line 1001 of /lib/badgeslib.php: call to message_send()
    line 486 of /lib/badgeslib.php: call to badges_notify_badge_award()
    line 558 of /lib/badgeslib.php: call to badge->issue()
    line 95 of /badges/action.php: call to badge->review_all_criteria()

Capability "mod/datalynx:notifymemberupdated" was not found! This has to be fixed in code.

    line 453 of /lib/accesslib.php: call to debugging()
    line 578 of /lib/messagelib.php: call to has_capability()
    line 187 of /lib/messagelib.php: call to message_get_providers_for_user()
    line 1001 of /lib/badgeslib.php: call to message_send()
    line 486 of /lib/badgeslib.php: call to badges_notify_badge_award()
    line 558 of /lib/badgeslib.php: call to badge->issue()
    line 95 of /badges/action.php: call to badge->review_all_criteria()

**Comment by michaelpollak** [comment]
Hey David,
I can't reproduce this yet, is this connected to the new author:badges datalynx extension? I tested it as a teacher and as a student role, works fine here. Where do you see these errors and in what capability do you see it?
Thank you for your clarification.

**Comment by michaelpollak** [comment]
Any update on this?

**Comment by dasistwas** [comment]
can not reproduce anymore so closing this.
