### ISSUE TITLE
URGENT: Invalid HTML output example: Duplicate ids for delete-buttons

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#27]
There is again a problem with HTML validation. That is not the only one:
```
<div class="form-control-feedback invalid-feedback" id="id_error_removeline">
            
        </div>
```
It would be good, that this does not happen in the future and all current problems should be solved.

**Comment by dasistwas** [comment]
![Uploading Screenshot_2019-04-21 Showing results for contents of text-input area - Nu Html Checker.png…]()

There are tons of duplicate ids. This is due to how fields in fieldgroups are rendered: There has to be an additional id for the line. Otherwise this will never be solved. Please solve all fieldgroup issues as top priority.

**Comment by michaelpollak** [comment]
Can't find any duplicate IDs anymore, will keep an eye on that.
