### ISSUE TITLE
Urgent feature: CSV import file

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#28]
There is an urgent feature request: When I import a CSV and in the field of type file is a web accessible link like https://www.virtuelle-ph.at/wp-content/uploads/2019/03/Infoblatt_OS_FrPr19-1.pdf then the file should be downloaded and saved in the appropriate file field.

**Comment by michaelpollak** [comment]
We only export one file and ignore if there are more. Is this an important usecase, if yes we should upgrade this functionality too. Thanks.

**Comment by dasistwas** [comment]
Hi,
@michaelpollak I added multi file support for import. Please merge dasistwas/develop. I think we can close this task?
Kind regards,
David

**Comment by michaelpollak** [comment]
Looks good to me, thank you.
