### ISSUE TITLE
URGENT: Saving / displaying and editing entries with fieldgroups does not work

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#29]
How to reproduce:

1. Add fieldgroup (settings: 1 required, 3 default, 10 max)
2. Add field time also to fg
3. Add field picture also to fg
4 Add field text also to fg
5. Add field editor also to fg
6. Add field textarea also to fg

Create grid view from default. Make it default view and edit view
Add one entry with one fieldgroup. Save.
Edit entry: add further 2 fieldgroups. Save.
Edit entry: Change the content of the 3 fieldgroups, Save.

Result: Content not changing, in view mode not all entries show up, and a lots of other issues. 

What causes those strange problems? We need to solve this and make it a solid solution.

**Comment by dasistwas** [comment]
Text is now saved. Problem with field of type picture.

**Comment by dasistwas** [comment]
TODO: Do not save empty fields in contents table (example: empty string). Delete those rows in DB instead.

**Comment by dasistwas** [comment]
The assumption things have been "visible to user" is not a valid assumption and is one of the origins of this bug. The concept to ignore certain submitted data is very dangerous. All submitted data has to be analysed.
https://github.com/dasistwas/moodle-mod_datalynx/blob/0fddcff6bbcb6cba7ccd94adf5066cf8daea1300/entries_class.php#L753

The iterator does not work either as the foreach is not in line with $i ($i differs from actual line number in the nested foreach loop).

**Comment by dasistwas** [comment]
Better approach could be: delete content from db when no data is submitted for the field.

**Comment by dasistwas** [comment]
What does not work: Removing the teammembers with the JavaScript "Delete" button does not work. They still appear when saving the form. 

Next step: Strategy for displaying and saving data in a solid way. Open for discussion:

### Approach 1

1. Add integer field to datalynx_contents table named rowid or lineid
2. Store the line of the fieldgroup there
3. Make deletion of content therefore easier: delete datalanx_contents where fieldid, entryid, rowid

**Comment by michaelpollak** [comment]
Rebuilt this as discussed.
We now process all data, collect where we do see empty fieldvalues and check if a line is completely empty.
If this is the case we remove all line contents from database.
I'm closing this to allow for more precise issue descriptions, filed issue is fixed.
