### ISSUE TITLE
Store line number in datalynx_contents

### ISSUE THREAD

**Issue by michaelpollak** [dasistwas/moodle-mod_datalynx#30]
To make it easier to sort and remove content lines we will add the lineid to the database table when update is used in a fieldgroups context, else keep lineid 0.
1) Add to database on update.
2) Look up all multiples for "entryid" and "fieldid" and update these lineids.
3) Extend content fetching.
4) Extend updating
5) Extend removing for all or specific line

**Comment by dasistwas** [comment]
How about keeping null for non fieldgroup fields? Add line numbers starting with 0 for fieldgroup fields? Updating could add general check for fieldgroup and not update every update function of every field.

**Comment by dasistwas** [comment]
0 is sometimes a problem when submitting formdata as it is also considered as false.

**Comment by michaelpollak** [comment]
To keep it backwards compatible I would default to 0, in case we add fields to a fieldgroup that have contents attached these become the first line.
You are right, 0 might be problematic in that sense. Maybe making it human readable and defaulting to 1 is the neater solution?

Currently trying to find and update the lineid of already stored content via SQL query for the upgrade.php

**Comment by dasistwas** [comment]
Nobody is using the feature yet. So that is not necessary

**Comment by michaelpollak** [comment]
Current implementation will be without linenumbers as discussed on our last phonecall.
