### ISSUE TITLE
Custom filter with identical names

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#31]
It is possible to add two custom filters with the same name in a datalynx instance. This should not be possible to do. So upon submission of a custom filter add a validation in order to prevent that.

**Comment by dasistwas** [comment]
Look at field renderer or field behavior to see example implementation.

**Comment by michaelpollak** [comment]
Added a validation here but errors are not shown after failed validation. Same goes for normal filters.

**Comment by michaelpollak** [comment]
Let me know if you need errors after validation fails, the form redirects to the overview and not to the actual form. If not needed this can be closed, thank you.

**Comment by dasistwas** [comment]
Errors display is always needed. Otherwise users do not know what went wrong.

**Comment by dasistwas** [comment]
Client validation?

**Comment by michaelpollak** [comment]
Thank you for the quick reply, will work on this now. 
I feel like client validation here is a hack, the forms should, if validation fails, redirect to itself and use the built in error messaging.

**Comment by michaelpollak** [comment]
Fixed this, if you agree I'd call this closed.
