### ISSUE TITLE
Add excerpt feature for field editor

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#32]
You can store a lot of text in the field editor. If you want to have a short preview of the text, then it would be good to have only the first characters displayed. So in addition to the [[fieldname]] there could also be a [[fieldname:excerpt]] pattern that is replaced with the excerpt instead of the full content. (Also with stripped HTML as plain text)

**Comment by michaelpollak** [comment]
Linking this commit here: https://github.com/dasistwas/moodle-mod_datalynx/commit/d3dd2494f990a539e5df5260596c6f70123af467

And this connected issue: https://github.com/dasistwas/moodle-mod_datalynx/issues/35

I suggest :excerpt makes sense and actually is a great idea. Implementation could be to render everything but only display a bit with a button to expand if a user wants to read further. This would keep the rule of "no duplicate fields in a view" intact and still add excerpt feature.
Maybe based on bootstraps collapse: https://www.w3schools.com/bootstrap/bootstrap_collapse.asp

**Comment by dasistwas** [comment]
This is also implemented.
