### ISSUE TITLE
Add New for Select (Multiple)

### ISSUE THREAD

**Issue by winnidat** [dasistwas/moodle-mod_datalynx#33]
After Add sort A to Z and put "Sonstige" on bottom

**Comment by winnidat** [comment]
After Add sort A to Z and put "Sonstige" on bottom

**Comment by dasistwas** [comment]
When rendered as autocomplete field it should be possible to add new items to a multi select field directly when editing an entry.

**Comment by michaelpollak** [comment]
Solid idea with using tags from autocomplete, I built the frontend elements of this but found some unexpected autocomplete behavior. As soon as I set "tags->true" values are not passed on. Working on that issue right now.

**Comment by michaelpollak** [comment]
Type of PARAM_INT blocked tag inputs. 
Some more quirks appeared, if I have a "a" in my select list autocomplete tries to pass an "a" along. Normal behavior is to pass along the numeric representation (eg. 1). If I enter 1 I get "a". Thinking up an algorithmic solution to this.

**Comment by dasistwas** [comment]
You could pass -1 for new value and then pass the new value as hidden element?

**Comment by dasistwas** [comment]
Oje, mein Bugreport:
https://tracker.moodle.org/browse/MDL-57680
Macht da Moodle ein single choice draus?

**Comment by dasistwas** [comment]
da dürfte Moodle das Verhalten der Option auch geändert haben.

**Comment by michaelpollak** [comment]
I don't think passing placeholders and hidden field is a good idea in this context. 

Autocomplete stays multiselect even if we put it in tag mode. 

Pushed an algorithm to make the data compatible and update field definition in the progress. Seeing an undefined index notice but getting there. I'll take a brake for now, have a nice afternoon.

**Comment by dasistwas** [comment]
Great solution, thanks! Works fine.
