### ISSUE TITLE
Adding more than 1 field of same type should be possible in a view

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#35]
Currently it is not possible to add more than one field of the same field type. 
Example:
Field named "Description" of type editor has 2 variants:
[[Description]]
[[Description:excerpt]]

If I add the 2 patterns in the entry settings of the view, I can not save the view due to an error message " You can not use the field Description more than once. "

**Comment by michaelpollak** [comment]
I've tested out your excerpt feature and it does not work as expected when used in an edit view. 
- I set up a dl instance with a editor field "tested".
- I disable validation checks in the code for testing.
- I set up grid view with tested and tested:excerpt.
- I add a new entry.

I see two text editors below each other where only one should be. The second should show up on the right hand side in the attached screenshot but as a textarea without controls.
![Bildschirmfoto von 2019-05-09 14-33-02](https://user-images.githubusercontent.com/475798/57453826-a95aaa00-7267-11e9-9a63-8e5bb756431e.png)

Also duplicates of fields in edit mode show weird results, I'd argue this should never happen.

I suggest :excerpt makes sense and actually is a great idea. Implementation could be to render everything but only display a bit with a jquery function to expand if a user wants to read further. This would keep the rule of "no duplicate fields in a view" intact and still add excerpt feature.

**Comment by michaelpollak** [comment]
If you agree with my suggestion I can start to implement this, thank you David.

**Comment by michaelpollak** [comment]
Seems addressed in #32, if so please close :) Thank you.

**Comment by dasistwas** [comment]
OK, I think we can close that for now.
