### ISSUE TITLE
Display of fieldgroup in PDF view

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#43]
In PDF view the fieldgroup should be displayed as a table with the fieldnames in the header of the table.
This should be done in the future by a special renderer for the field of type fieldgroup, but meanwhile a special template for PDF view should to the trick.

**Comment by dasistwas** [comment]
Wip in new branch: pdf-fldgrps 7bc27a4dbd3a9d27f2a380fa1ab38a74f710db79

**Comment by michaelpollak** [comment]
Thank you for your nice draft David, that method works amazingly well. Didn't think of that yet, will keep this trick in mind for future development.
Fixed it up so now it does produce a valid pdf, looking good for only a few cols but gets ugly if fieldgroup uses a lot of fields. Either we make the font smaller or break lines somehow. Working on a solution now.

**Comment by michaelpollak** [comment]
Weirdly this is not documented, if we don't have any headers we don't show <th> to pass validation.
https://docs.moodle.org/dev/Templates#Test_for_not_empty_array_in_a_mustache_template

**Comment by michaelpollak** [comment]
I've seen your styling of the table but travis throws an error at it, in html5 padding and spacing is obsolete.
` <table class="table table-striped" style="width: 100%;" cellpadding="5" cellspacing="0">`

Removed these in my codebase and validates fine now, if it is important we need to extend the css.

**Comment by dasistwas** [comment]
CSS does not seem to work very well with PDF output. Hope we find a way in order to have cellpadding without validation problems.
