### ISSUE TITLE
After backup / restore error message due to not backing up / restoring fields in fieldgroup

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#46]
`

Exception - Call to a member function for_use_in_fieldgroup() on boolean

More information about this error
Debug info:
Error code: generalexceptionmessage
Stack trace:

    line 185 of /mod/datalynx/field/fieldgroup/renderer.php: Error thrown
    line 47 of /mod/datalynx/field/fieldgroup/renderer.php: call to datalynxfield_fieldgroup_renderer->get_subfields()
    line 155 of /mod/datalynx/field/renderer.php: call to datalynxfield_fieldgroup_renderer->render_display_mode()
    line 303 of /mod/datalynx/field/field_class.php: call to datalynxfield_renderer->replacements()
    line 1255 of /mod/datalynx/view/view_class.php: call to datalynxfield_base->get_definitions()
    line 1230 of /mod/datalynx/view/view_class.php: call to datalynxview_base->get_entry_tag_replacements()
    line 1157 of /mod/datalynx/view/view_class.php: call to datalynxview_base->get_entries_definition()
    line 1116 of /mod/datalynx/view/view_class.php: call to datalynxview_base->definition_to_html()
    line 588 of /mod/datalynx/view/view_class.php: call to datalynxview_base->display_entries()
    line 768 of /mod/datalynx/classes/datalynx.php: call to datalynxview_base->display()
    line 55 of /mod/datalynx/view.php: call to mod_datalynx\datalynx->display()`

The reason seems to be, that the fieldgroup does not have any field anymore. So backup/restore does not include the fields of the fieldgroup in the fieldgroup settings on backup/restore.

**Comment by dasistwas** [comment]
[sicherung-moodle2-activity-3-datalynx3-20190526-1504-an.zip](https://github.com/dasistwas/moodle-mod_datalynx/files/3220342/sicherung-moodle2-activity-3-datalynx3-20190526-1504-an.zip)

**Comment by dasistwas** [comment]
Rename uploaded file to mbz after downloading.

**Comment by michaelpollak** [comment]
Looking into this right now, assumption is that subfields have different fieldids after restoring. This leads to missing subfield definitions and thus can not work. 
Solution is to remember new fieldids of subfields and update definition of fieldgroup.

**Comment by dasistwas** [comment]
Yes exactly. There are strategies for doing that in Moodle backup/restore process. https://docs.moodle.org/dev/Backup_2.0_for_developers

**Comment by michaelpollak** [comment]
Travis is happy, my tests worked fine, I'd call this closed. Thanks David.
