### ISSUE TITLE
Data of field of type text with field setting "Autocomplete" is not deleted in fieldgroup when clicking on delete button

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#47]
How to reproduce

1) Add field of type text named "mytext" make it an autocomplete field
2) Add some other field "random"
3) Add fieldgroup named "myfieldgroup" and add field "mytext" and "random" to the fieldgroup
4) Create a grid view (default and editing)
5) Add an entry with 2 repeating fields
6) Edit the entry and try to delete the last row of the entry -> value in "mytext" is not removed.

**Comment by michaelpollak** [comment]
Wasn't aware of autocomplete in text, implementation is with single select option so the x we click in teammemberselect is not visible. Was able to change it in JS but some JS within autocomplete blocks changes and makes it visible only after a second click on delete.

**Comment by dasistwas** [comment]
Fixed in f0514056e6d23aa69e52770da72ad5f4029aaff9 just reordering of JS calls solved the problem.
