### ISSUE TITLE
Fieldgroups: Random attribution of field values in different lines when some fields in a line are deleted

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#48]
To test use this dl instance (rename zip to mbz). The instance includes all field types useable for a fieldgroup. As backup/restore of fieldgroups does not work, fields have to be added again to the fieldgroup after restore.
[backup-moodle2-activity-469-datalynx469-20190527-1013-an.zip](https://github.com/dasistwas/moodle-mod_datalynx/files/3222524/backup-moodle2-activity-469-datalynx469-20190527-1013-an.zip)

**Comment by michaelpollak** [comment]
Can't reproduce this yet, was thinking this may be connected to #47  but can't find any evidence for that.

**Comment by michaelpollak** [comment]
Changes in the way autocomplete fields pass data between mdl 3.5.1 and 3.5.6 cause this issue. Teammemberselect should be fixed, testing tms and checking all other field classes that (can) use autocomplete.

**Comment by dasistwas** [comment]
Thank you for implementing backward compatibility as well.
