### ISSUE TITLE
Add possibility to merge uploaded PDFs with PDF export

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#52]
When a PDF is generated in the PDF-view and a PDF was uploaded in a file field, then it should be merged with the generated PDF. 

@michaelpollak Could you do a research how this could be implemented. Datalynx uses TCPDF, but Moodle also provides fpdi or fpdf framework in order to achieve that.

https://stackoverflow.com/questions/1630016/creating-a-new-pdf-by-merging-pdf-documents-using-tcpdf

**Comment by michaelpollak** [comment]
Travis does not like fpdi... 
No matter if we use ghostscript or fdpi we need to access the local path of the file, working on that now.

**Comment by dasistwas** [comment]
https://tracker.moodle.org/plugins/servlet/mobile#issue/MDL-60301

**Comment by michaelpollak** [comment]
This feature looks good,
we collect all the appropriate pdf files that are available in the view (not all from context!) and import them with fpdi into our final pdf export. This uses the fpdi lib available in the core but weirdly placed in /mod/assign/feedback/editpdf/fpdi/ which extends tcpdf.
My tests work fine with different usecases, as always I very much appreciate your feedback.

**Comment by dasistwas** [comment]
Great work! Works like a charme.
