### ISSUE TITLE
Add global search

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#53]
Moodle global search does currently not index datalynx search. So this should be implemented. https://docs.moodle.org/dev/Search_API

**Comment by michaelpollak** [comment]
For testing make sure /admin/settings.php?section=manageglobalsearch shows that the indexes are up to date.

**Comment by dasistwas** [comment]
That would be good to have datalynx entries being able to be searched. But not a priority right now.

**Comment by dasistwas** [comment]
This PDF makes problems when adding it.
[190903_HW_WS Erweiterung_Protokoll.pdf](https://github.com/dasistwas/moodle-mod_datalynx/files/3627520/190903_HW_WS.Erweiterung_Protokoll.pdf)

**Comment by michaelpollak** [comment]
Tested it a little more yesterday and I am happy with this fix :)

**Comment by dasistwas** [comment]
Yes, works great. Thank you!
