### ISSUE TITLE
Make it possible to override view filter

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#55]
Current situation: When a filter is defined in the view settings, then it is not possible to add a custom filter to the view. It should be possible to override this filter with a custom filter, that is added to the view template. So there should be a checkbox in the view settings in order to make it possible to override the predefined filter with the filter in the view settings. The checkbox must be unchecked per default, as this is a security issue: Sometimes a filter is used in order to prevent people to see entries they are not allowed to see: Example: They can just see entries they created. So only when the checkbox is activated overriding the filter with a custom filter should be possible.

**Comment by michaelpollak** [comment]
As I read it this is a duplicate of https://github.com/dasistwas/moodle-mod_datalynx/issues/70 and thus fixed already :) 
Good problem to have.
