### ISSUE TITLE
Can not edit existing customfilter

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#56]
Editing an existing filter results in error upon saving to change the filter name. 

![Screenshot_2019-06-23 Datalynx import files Benutzerdefinierte Filter (Verwaltungsmodus)](https://user-images.githubusercontent.com/1620975/59981443-b0fdc480-9603-11e9-83a4-cd7f3ae3fc2b.png)

**Comment by michaelpollak** [comment]
I'd call this fixed, thank you David.

**Comment by dasistwas** [comment]
Perfect thanks.
