### ISSUE TITLE
When adding a "tag" field to the custom filter, the search returns an error

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#57]
When adding a custom filter to a view, that includes a tag-field, and I search for a specific tag, then the search returns an error.

**Comment by michaelpollak** [comment]
Tags are stored as csv in content table (tag1,tag2) , multiselect assumes #tag1#,#tag2# notation. 

I changed the tag get_search_sql function to act like the multisel but removed the hash separators. This makes it pretty problematic as "tag1" would be returned even if I look for "tag12". But it works.

If this is the accepted fix I will write some code to make it more precise without introducing separators.

**Comment by dasistwas** [comment]
Why remove the #? So you could search for #tag1#

**Comment by dasistwas** [comment]
LIKE '%#tag1#%'

**Comment by dasistwas** [comment]
Also altering data structure in dB requires upgrade action.

**Comment by michaelpollak** [comment]
Sorry, not clear enough on my part.
Tags are stored as csv like "tag1, tag2, tag3"
Multiselect fields are stored with separators "#tag1#, #tag2#, #tag3#"

I used the code from multiselect but changed in the fieldclass tag to not use separators. No need to upgrade database of course. I'm still trying to figure out how tags are supposed to work, maybe I have some misunderstanding here.

**Comment by michaelpollak** [comment]
I will work on this some more tomorrow, there should be a reason why we use this intermediate DB query instead of just looking at the table. Just looks weird to me, maybe you have time to explain. Thanks a lot.
