### ISSUE TITLE
Field teammemberselect: Minimum size of 1 requires 2 team members

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#58]
When adding a teammemberselect field (tms) with minimum number of members set to 1 in the settings, a minimum number of 2 members is required when saving an entry.

**Comment by michaelpollak** [comment]
Autocomplete functionality was changed, made this check backwards compatible, works now with mdl 3.5.6+.

**Comment by dasistwas** [comment]
Perfect, works fine now. Not sure though for the fieldgroup. But will be another issue if that problem is confirmed.
