### ISSUE TITLE
Filter problem: I am teammember + ordering by title

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#59]
ERROR: Mixed types of sql query parameters!!

**Comment by dasistwas** [comment]
Error happens when more than 1 team member and ordering by text field is defined in the filter settings.

**Comment by dasistwas** [comment]
Debug info: Unknown column 'c1164.fieldid' in 'where clause'
SELECT COUNT(e.id) FROM vphonline___datalynx_entries e
JOIN vphonline___user u ON u.id = e.userid
LEFT JOIN vphonline___groups g ON g.id = e.groupid LEFT JOIN
(SELECT r.itemid, r.component, r.ratingarea, r.contextid,
COUNT(r.rating) AS numratings,
AVG(r.rating) AS avgratings,
SUM(r.rating) AS sumratings,
MAX(r.rating) AS maxratings,
MIN(r.rating) AS minratings,
ur.id as ratingid, ur.userid as ratinguserid, ur.scaleid, ur.rating AS usersrating
FROM vphonline___rating r
LEFT JOIN vphonline___rating ur ON ur.contextid = r.contextid
AND ur.itemid = r.itemid
AND ur.component = r.component
AND ur.ratingarea = r.ratingarea
AND ur.userid = ?
WHERE r.contextid = ?
AND r.component = ?
AND r.ratingarea = ?
GROUP BY r.itemid, r.component, r.ratingarea, r.contextid, ratingid, ur.userid, ur.scaleid
ORDER BY r.itemid) AS er ON er.itemid = e.id WHERE e.dataid = ? AND ( (e.id <> ?) OR ( ( (e.id <> ?) AND c1164.fieldid = 1164 )))
[array (
0 => '25',
1 => 195313,
2 => 'mod_datalynx',
3 => 'entry',
4 => '116',
5 => '5337',
6 => '5337',
)]
Error code: dmlreadexception

**Comment by michaelpollak** [comment]
Fixed this yesterday, problem was that the "empty" check was not added to OR linked terms. I built a function so this can never happen again and we use the same checks for AND and OR terms.
