### ISSUE TITLE
Custom filter: Add possibility to search for entry author

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#61]
Add setting in custom filter settings to search for author, add  search function.

**Comment by michaelpollak** [comment]
Travis is happy with this fix, calling this done.

**Comment by dasistwas** [comment]
Not yet done: Custom filter search form is not very helpful. Search should be done via autocomplete field.

**Comment by michaelpollak** [comment]
It actually is an autocomplete field already, I noticed two lines of code that broke the feature and marked it up there. Could you please explain what these lines should do? It's unclear to me.

**Comment by michaelpollak** [comment]
If these two offending lines are not important I think this issue is solved :)

**Comment by dasistwas** [comment]
2 additional enhancements:

1) I do not see any label for the author field
2) The author list that can be searched: Only show authors already present in at least one of the entries

**Comment by michaelpollak** [comment]
Extended this fix yesterday, travis is happy.

**Comment by dasistwas** [comment]
Great. Only users are shown, who have already written an entry. So everything is perfect.
