### ISSUE TITLE
Cron job problem 

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#63]
Running cronjob throws the following error (I assume to reproduce there has to be a rule that notifies upon updates of teammembers:

`</pre>++ Capability "mod/datalynx:notifymemberupdated" was not found! This has to be fixed in code. ++
* line 453 of /lib/accesslib.php: call to debugging()
* line 578 of /lib/messagelib.php: call to has_capability()
* line 187 of /lib/messagelib.php: call to message_get_providers_for_user()
* line 813 of /lib/classes/update/checker.php: call to message_send()
* line 625 of /lib/classes/update/checker.php: call to core\update\checker->cron_notify()
* line 213 of /lib/classes/update/checker.php: call to core\update\checker->cron_execute()
* line 49 of /lib/classes/task/check_for_updates_task.php: call to core\update\checker->cron()
* line 105 of /lib/cronlib.php: call to core\task\check_for_updates_task->execute()
* line 67 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
* line 61 of /admin/cli/cron.php: call to cron_run()
<pre>
`

**Comment by michaelpollak** [comment]
We don't have the capability notifymemberupdated, fixed as I am confident it ment to say notifyteamupdated. 
This also should fix the error you encountered here: https://github.com/dasistwas/moodle-mod_datalynx/issues/23
