### ISSUE TITLE
Custom filter: Add time field for sort/search

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#64]
Currently the field of type time ist not included in the custom filter. The field should be added and sortable.

**Comment by michaelpollak** [comment]
Fixed search as well. 
Simplified interface to work with customfilter parsing.
Also fixed buggy default case as "ANY_OF" does not make sense with times and was not used. Made "BETWEEN" default case and made customsearch work like that.

Tested sorting and searching, both work as expected. Waiting for behat to do its thing and would call this fix done. Looking forward to your feedback.

**Comment by dasistwas** [comment]
Works well, but once set a date to search for I can not remove the date search anymore or make the search criteria "empty"

**Comment by michaelpollak** [comment]
Date/Time moodle form fields do have an optional argument that can disable it and pass 0 as a form value, see https://github.com/moodle/moodle/blob/aaff6692a1aa1827cb5c1c69910302d8cbf99379/lib/form/datetimeselector.php#L55

I have added this to the fromtime field, so one can easily tick this to "empty" the value. totime is now() by default and I feel like this does not need disabling. 
Maybe we can think about updating all date/time fields with this optional value, currently we render a checkbox separately. 

I'd argue this resolves your comment, thanks.

**Comment by dasistwas** [comment]
Yeah. Great additional feature! Works as expected. Thank you.
