### ISSUE TITLE
Error on restore: missing grade xml file

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#65]
Backup is missing XML file: [tempdir]/backup//66f499dab4d5bceac487b4b16f559838/activities/datalynx_189/grades.xml

Information about the error: https://docs.moodle.org/36/en/error/moodle/missing_moodle_backup_xml_file

**Comment by dasistwas** [comment]
happens upon restore from frontpage to course.

**Comment by dasistwas** [comment]
Same error when restoring forum. So maybe a core bug.... 

Backup is missing XML file: [tempdir]/backup//dc703247cc009f245e73a2ccb05c4ab2/activities/forum_317/grades.xml

**Comment by michaelpollak** [comment]
Still can't reproduce that, any more info about that error or a backup file that I can test with?

**Comment by dasistwas** [comment]
As this happens also with forum I do close this for now considering as a core bug.
