### ISSUE TITLE
Restrict mimetypes for file uploads.

### ISSUE THREAD

**Issue by michaelpollak** [dasistwas/moodle-mod_datalynx#67]
When a teacher creates a field of type file she/he should be able to restrict mimetypes. 
Add an autocomplete field to the form, fetch possible mimetypes from moodle.

**Comment by michaelpollak** [comment]
Found a bug that should be corrected in old data. 
Possible Restrictions for field type file were *, image and .html but ".html" is not a valid mimetype! So everytime a field was setup with param3 as ".html" the user sees an error message and cannot upload any files.

I propose to **check your database for fields where param3 is .html and change all occurences to html** to fix this.

**Comment by dasistwas** [comment]
Right now, the restriction is only single choice. Maybe I can implement a quick fix now. Also, if possible also providng the mime type name in addition to the file extension in the selection list of the field settings would be nice.

**Comment by dasistwas** [comment]
OK, I think single choice is OK for now. Added improved description for selecting mimetypes. Features works fine.
