### ISSUE TITLE
Travis fails after upgrade

### ISSUE THREAD

**Issue by michaelpollak** [dasistwas/moodle-mod_datalynx#68]
Travis fails when I am building datalynx bc. mysql is not reachable.

**Comment by michaelpollak** [comment]
I changed the travis config file because the mysql service was not started. 
Changes are here: https://github.com/michaelpollak/moodle-mod_datalynx/commit/73d489f2936c41b67b7848c982bb44f4b6848c76
Documented here: https://github.com/blackboard-open-source/moodle-plugin-ci/issues/92

This fixes the first problem but moodle-plugin-ci mustache also is broken so build is not yet ok. Code is.

**Comment by michaelpollak** [comment]
I assume the integration team will fix this bug in time for us.
Bc. currently nothing is changed in mustache templates I removed this test and added a note to my calender. Will check if integration is working in a week. Our builds are working again, closing this bug for now and will reopen if not solved until September.

**Comment by michaelpollak** [comment]
Behat errors still, working on that...

**Comment by dasistwas** [comment]
that is more a setup problem of https://github.com/dasistwas/moodle-mod_datalynx/blob/develop/.travis.yml Maybe we have to update that in order to make behat work again. There seems to be a problem with Selenium and/or Chromium driver.

**Comment by michaelpollak** [comment]
Bugs were introduced when xenial became default build environment, see: 
https://changelog.travis-ci.com/xenial-as-the-default-build-environment-99476
https://docs.travis-ci.com/user/reference/xenial/
https://docs.travis-ci.com/user/gui-and-headless-browsers/
https://gitmemory.com/issue/blackboard-open-source/moodle-plugin-ci/99/503171079
https://tracker.moodle.org/browse/MDLSITE-5739
https://travis-ci.community/t/xenial-not-wanting-to-start-xfvb/2397/4
https://github.com/moodlehq/moodle-local_ci/pull/198
https://github.com/blackboard-open-source/moodle-plugin-ci/issues/91

Selenium works as expected now, closing this and rechecking in two weeks.

**Comment by michaelpollak** [comment]
Mustache validation was tested and works as expected. Closing this issue for real now.
