### ISSUE TITLE
New view setting: Override default filter

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#70]
There should be a new view setting: Checkbox in order to make it possible to override the default filter set in the view settings with a user filter or custom filter. Default: Not checked. 
This has some security relevance, because when a filter is chosen and it can be overriden users could potentially see data they should not see. So implementation has to take care, that this can not happen.

**Comment by michaelpollak** [comment]
Tried to think of a way to reduce the possible security implications. As we don't mark what data should be kept secret and what is public the tool can't really overrule the admins on this issue. I have added some language strings to explain the possible problem and was thinking about adding a second step to enable this feature. 
Can you think of an algorithmic way to check the visible information?

Other than that this enhancement is ready, looking forward to your ideas. Thank you David.

**Comment by dasistwas** [comment]
This issue is independent from roles. Right now when a filter is applied in the view settings, it stays applied no matter what role you have. So that should be kept. 
When enabling the checkbox, the filter is only applied when no other filter is applied. So that makes it possible for everyone to override the filter. It gets a default filter instead of a "forced" filter for the view.
Does that answer your question?

**Comment by michaelpollak** [comment]
I get the problem filteroverride introduces but don't know how to fix it with an algorithm. We don't have any way to determine if information is suitable for everyone or should be kept secret without human interaction. 

An example may help. 
I set up a view and show a student only projects where he/she is a teammember. That would be a classic usecase for a forced filter.
Now I enable filteroverride and a student can select to see all projects.
Maybe now he/she can also see details of other projects, uploaded presentations or exam-answers. Only a human can determine if uploaded presentations are save to share or should be kept secret, datalynx only sees a field of type file.

**Comment by dasistwas** [comment]
The view does now.

**Comment by dasistwas** [comment]
Call?

**Comment by dasistwas** [comment]
If a user should not access a view with a filter, that can be overridden, the access to this view should not be allowed.

**Comment by michaelpollak** [comment]
I tested a bunch of usecases and was able to apply a filter despite a forced filter was set. Fixed that by using is_forcing_filter() in set_filter. Thanks for the clarifying phonecall David.

If I set nothing Filters can be chosen by user.
If I set a filter, nothing can be chosen by user or URL parameter.
If I set a filter and filteroverride choice is reestablished and URL parameters work.

**Comment by dasistwas** [comment]
Thank you. Also my tests did go well.
