### ISSUE TITLE
Line breaks in radio button edit view

### ISSUE THREAD

**Issue by michaelpollak** [dasistwas/moodle-mod_datalynx#71]
When adding a radio button field and display edit view the first button has an inline description while all the following have a linebreak. 

![grafik](https://user-images.githubusercontent.com/475798/64236018-d8bdb280-cef9-11e9-941a-28ab737cde3a.png)

### Expected
Display inline if possible and next line only if text is too long.

**Comment by michaelpollak** [comment]
Third parameter of radio buttons is ignored when used in groups. https://docs.moodle.org/dev/lib/formslib.php_Form_Definition#radio 

At some point the $separator was used as third parameter which introduced <br> in the html render. Removal fixed this issue.

**Comment by dasistwas** [comment]
works now, but still form html is a mess. I opened another issue for that.
