### ISSUE TITLE
Include comment in the comment event notification

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#74]
Right now when the event notification "Comment added" is triggered, an e-mail ist sent, but without including the comment itself. So It would be cool to have the comment included in the e-mail.

**Comment by michaelpollak** [comment]
Good morning David. 
As this is marked urgent you can use it already, please look over it and give it a quick test, it will be fine. Travis still fails bc. of some internal error, I will keep an eye on it. Thank you.

For future reference, the $event has no information about the comments text in it and the comment interface is overkill for our usage. We simply look it up in the comments database table bc. we know the id.

**Comment by dasistwas** [comment]
Thank you for closing this. Generally I would prefer to do that myself after testing. In automn there is always a lot to do so testing may be done a  little bit later...

**Comment by michaelpollak** [comment]
Wasn't sure if you just forgot, thanks for the info. 
Hope the semesterstart is going well, have a nice day.

**Comment by dasistwas** [comment]
I do not get the message. Just get that:

> Hello Heidelinde Bogner,
> 
> a comment to one of your entries was added by Heidelinde Bogner.
> 
> The following entry has been commented on: Link to entry. 

Do I miss something?

**Comment by dasistwas** [comment]
After purging caches, I get that:

> Hello Heidelinde Bogner,
> 
> a comment to one of your entries was added by Heidelinde Bogner.
> 
> The following entry has been commented on: Link to entry,
> this text was added: "{$a->commenttext}" 

Also the wording could be improved.

**Comment by dasistwas** [comment]
I will fix that.

**Comment by dasistwas** [comment]
Wrong DB query: get_field instead of get_record. Also an unnecessary condition was added.
