### ISSUE TITLE
Exception when including rating:rate

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#76]
When including the tag ##ratings:rate## in entry view I get this error:

Exception - Call to undefined method datalynxfield__rating_renderer::help_icon_scale()

**Comment by michaelpollak** [comment]
Checked this out, happens only when non-numeric ratings are available. Can confirm it is a very old bug. Solution is to use $OUTPUT to create this html code, works in my tests, patch soon.

_On a sidenote, it seems this bug also affects mod_booking._

**Comment by dasistwas** [comment]
I am working on it. Help button not helpful so removing it

**Comment by dasistwas** [comment]
OK you have been faster ;-)

**Comment by michaelpollak** [comment]
Oh ok, sorry for the misunderstanding. By coincidence I've just started up moodle to play with it and get some github issues closed :) 
Have a nice day David.
