### ISSUE TITLE
Custom filter: teammemberselect does not work

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#8]
When creating a custom filter and adding the field of type teammemberselect to it, the filter form is not rendered correctly and probably also not working correctly. It apparently is not using the method     

> public function render_search_mode(MoodleQuickForm &$mform, $i = 0, $value = '') {

Please also test the custom filter form a little bit. There might be additional bugs.

**Comment by michaelpollak** [comment]
When I add a filter and add a field teammemberselect it is rendered and works as expected. I only can pick one teammember per line but I think that is by design. I have been testing this all morning and feel like it does what it is supposed to do. Anything specific you tried that failed?

**Comment by michaelpollak** [comment]
3.5

**Comment by michaelpollak** [comment]
Making some progress here, so the multiple input fields bug was introduced by this code, view_class.php:1258 _// Enables view tag replacement within the entry template._

I don't understand why this would be needed but I feel like view tags that have been displayed in the view template can be hidden for every following entry. As soon as get_replacements is called we create too many input fields. Filter is not working as expected, I will work further to determine if other view tags can handle being called multiple times gracefully.

**Comment by dasistwas** [comment]
Still to fix: In the tab navigation, the filter is called "User filter", but it should be called "Custom filter".

**Comment by dasistwas** [comment]
The search for the field teammemberselect does still not work. I also tested the same search with the advanced filter. There the filter works. So maybe have a look how it is done there in order to solve the problem.

**Comment by michaelpollak** [comment]
Ah I see the last commits were not linked, sorry.
The combination of multiple filters has been a problem, as empty values were not removed from the queries. This was not intended. 
Fix: https://github.com/michaelpollak/moodle-mod_datalynx/commit/07405de609e5be4d8151c591c7b84408fe697d3f

Lang files have been edited: https://github.com/michaelpollak/moodle-mod_datalynx/commit/583f793a13d016c5d86d5166b1c4156c3ae4f20a

**Comment by michaelpollak** [comment]
https://github.com/michaelpollak/moodle-mod_datalynx/commit/9ff15ca63fbbe51d0625ec994da2cb21605beca5

Sorting fix, I will test some more but this looks good.

**Comment by dasistwas** [comment]
Thank you for fixing this. Tested again and seems to work fine now. There was still a problem when you have two equally named custom filters. Fixed SQL for that as well in 8085d5e
