### ISSUE TITLE
Authorsearch does not to seem work properly

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#82]
When adding authorsearch to the custom filter, there should be a autocomplete field rendered. Right now it is a text field. Also the label is misleading in the search/filter form

**Comment by michaelpollak** [comment]
I am not sure I read this correctly. Authorsearch is #61, there I added an autocomplete :) Can you tell me what label you find misleading? Authorsearch or the german "AutorInnensuche"? We could write "Entry author"?

**Comment by michaelpollak** [comment]
Still not really clear what to make of it, if the issue is solved in #61 please close, thank you.

**Comment by dasistwas** [comment]
OK, closing this, but there is still a problem
