### ISSUE TITLE
customfilter is shown when editing entry

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#83]
Custom filter is shown when editing an entry. It should not be shown.

**Comment by michaelpollak** [comment]
This patch does not show customfilter when user is editing. All other filters are still shown, not sure if that is intended.
I will simplify this function a bit because it got pretty ugly over time :)

**Comment by michaelpollak** [comment]
This fix is ok to use, if filters should be hidden as well we can open a new issue. Thank you.

**Comment by dasistwas** [comment]
No filters should not be shown.

**Comment by michaelpollak** [comment]
Hid filters as well, should be solved now. Thanks for your feedback David.

**Comment by dasistwas** [comment]
Great fix. Thank you.
