### ISSUE TITLE
Custom filter: Combining Search string with another filter option broadens search instead of narrowing it

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#85]
How to reproduce:
1) Create a custom filter with a text search and filter options
2) In a view apply a search string and a filter option (example: team member)
3) Apply the filter

Result: All entries either with the search string **OR** the team member are shown.
Expected result: Only entries containing the team member **AND** the search string should be shown

**Comment by michaelpollak** [comment]
Tried to reproduce that bug.
Set up a new instance, added a textfield and a teammember field.
Put a customfilter for both fields and added some testdata

I looked for specific strings, worked. Also looked for teammembers, worked as expected. Combining the two customfilters got me the expected result by combining the two statements with an AND query. 

So maybe I got something about your report wrong but I can't reproduce it here at the moment, looking forward to more information on this. Thank you.

**Comment by dasistwas** [comment]
Apparently, this is only an issue with team member select and full text search. Using author search and full text search works great.

So I try to describe a little bit further:
In an entry there is no team member "Leilani Abbott" but I have the text "Digital" in the entry. When I search for "Digital" in full text search and "Leilani Abbott" I get the entry where I have the word "Digital" in it. But correct result would be no entry at all because, all 2 search conditions should be met.

**Comment by michaelpollak** [comment]
Thank you, that is reproducible now. I've read "textsearch" as search in a textfield - which works flawlessly.
I'm looking into that now, have a nice day David.

**Comment by michaelpollak** [comment]
Previously search terms were OR linked for some reason. To narrow down multiple search values reset these to be AND linked.
This changes functionality significantly and should be added to the changelog documentation.

**Comment by dasistwas** [comment]
I do not think search terms were OR linked. It is AND between different fields usually and for multi select it was OR inside multiselect. Example

fulltextstring AND (radio1 OR radio1 OR radio4) AND authorname AND textfieldvalue

**Comment by dasistwas** [comment]
@michaelpollak Please give me an update about progress here.

**Comment by michaelpollak** [comment]
Good morning David,
this issue is also solved. The change I introduced in 526fc27 was correct, have you tested the implementation? 

Basically these two lines are correcting the issue we are talking about:
```
$searchwhere[] = ' (' . implode(' OR ', $searchlike) . ') ';
$wheresearch = $searchwhere ? ' AND (' . implode(' AND ', $searchwhere) .')' : '';
```

 Above line does the "radio1 OR radio4" and the second line "AND authorname AND taxtfieldvalue". IMHO this is the fix, looking forward to your feedback, thank you.

**Comment by michaelpollak** [comment]
The customfilterqueries are AND linked to all the quicksearch queries.
```
AND ( ( customfiltertext ) AND  ( allthesimplesearch ) )
```
instead of previously: 
```
AND ( ( customfiltertext ) OR  ( allthesimplesearch ) )
```

**Comment by dasistwas** [comment]
Thank you, tested and works great now.
