### ISSUE TITLE
Filter: Teammemberselect should be rendered same way as radio

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#86]
Currently it is not possible to empty the autocomplete field for teammemberselect in the custom filter form. Once a team member is selected it can not be removed, only replaced by another team member. 
When I use a radio button in the filter form, this works perfect: I can select one more or none, also I can remove all options from the form. So render the teammemberselect form exactly like the radio form in the filter form.

**Comment by michaelpollak** [comment]
Radiobutton extends select and implements the attribute "multiple" for autocomplete fields. Teammembers expects only one name in the search query, so if I add the attribute multiple it is easy to remove a name but also possible to add multiple, only one is saved at that point.
If it is important to look for more than one name we need to implement this.

**Comment by dasistwas** [comment]
Should work exactly like radio: When I select more team members, then one of these team members should be in the entry. Same with authorsearch field.

**Comment by dasistwas** [comment]
@michaelpollak please give update on progress

**Comment by michaelpollak** [comment]
Sorry, thought this was clear, issue is fixed and my tests were successful. :)
Updated tms and authorsearch to be able to remove all names or add multiple, same as radio button.

**Comment by dasistwas** [comment]
feels great now
