### ISSUE TITLE
FPDI error in Moodle 3.8

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#87]
The fpdi class setasign has to be included differently. I think we have tu use namespace instead of require_once.

Zeile 29:
-require_once("$CFG->dirroot/mod/assign/feedback/editpdf/fpdi/fpdi.php");

It would be good, if the solution is backward compatible up to M3.5

**Comment by dasistwas** [comment]
@michaelpollak this is urgent, would be cool if you could prioritise it.

**Comment by michaelpollak** [comment]
Thanks for the heads up David, will work on it this evening. Do we switch main testing completely to 3.8 now?

**Comment by dasistwas** [comment]
We have to support from 3.5 to 3.8. So developing on 3.5 and testing on 3.8 would be good. But I will do testing on 3.8, so you can develop on 3.5 and add travis support for 3.8.

**Comment by michaelpollak** [comment]
Depending on the existence of autoload.php we can dynamically load what class we want to extend. Full disclosure, I found the idea here: https://stackoverflow.com/questions/1539530/is-it-possible-to-extend-a-class-dynamically

Tested with 3.5 and 3.8 and it works as expected, please check if this is an appropriate fix for you. Thanks.

**Comment by dasistwas** [comment]
Great research results and great fix. Maybe still include a todo in the code comment in order to remove that dynamic class when we end support for M3.5
