### ISSUE TITLE
Filter teammemberselect is empty does not work

### ISSUE THREAD

**Issue by michaelpollak** [dasistwas/moodle-mod_datalynx#9]
When I add a filter and add a search option for a teammemberselect field and select "is empty" the created sql query does not work.

**Comment by michaelpollak** [comment]
[This is the first commit for that fix](https://github.com/michaelpollak/moodle-mod_datalynx/commit/48c8a88e3cdbe813a73b38d4a360b013f9411e9e), forgot to add the issue number to the commit message.


We check if the filter option is empty and don't add fieldid in this case that causes the error.

**Comment by michaelpollak** [comment]
This changed as the autocomplete now stores [] in an empty tms content field.

**Comment by michaelpollak** [comment]
https://github.com/michaelpollak/moodle-mod_datalynx/commit/7293f6b5d474c76a7a66b9f221100c26e6c91a38
This fix is backwards compatible with either '' or [] for empty teammemberselect fields. If you agree this can be closed, thank you.

**Comment by dasistwas** [comment]
Perfect! Thank you for the fix.
