### ISSUE TITLE
Add a "Reset filter" button to custom form

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#91]
Right now it is difficult to clear a filter. So a "Reset filter" button should be added to the custom form.
Simple way: Just render the link to the view with &filter=0 as GET variable and so the filter is cleared.

**Comment by dasistwas** [comment]
Interesting solution with onclick. This is not the best way to attach an event handler according to https://stackoverflow.com/questions/1070760/javascript-function-in-href-vs-onclick . So maybe an a element with class="btn btn-secondary" would be better like `<a href="link" class="">Reset filter</a>`

**Comment by michaelpollak** [comment]
I tested out your idea and alignment just is not right. Your concerns are valid, thanks for pointing it out. I will look into somehow link the button but wasn't able to find anything yet.

![grafik](https://user-images.githubusercontent.com/475798/75178185-ebda6e00-5737-11ea-81dd-b01d42f44bb0.png)
_(below is normal button, above is html or static)_

**Comment by dasistwas** [comment]
Positionierung kann man mit Klasse d-block beeinflussen. Oder einen wrapper machen. https://v4-alpha.getbootstrap.com/utilities/display-property/

**Comment by michaelpollak** [comment]
I slept over it, using the mform element static is imho the right choice, leaving alignment to the forms api. It does look right on all the weird customfilters I have tested, thank you for your feedback David :)

**Comment by dasistwas** [comment]
Could we add a class "pull-left" in order to have both buttons in one line?

**Comment by dasistwas** [comment]
If that is not possible with standard methods, then please close that issue.

**Comment by dasistwas** [comment]
Thank you, this works fine now.
