### ISSUE TITLE
Custom filter in accordeon

### ISSUE THREAD

**Issue by dasistwas** [dasistwas/moodle-mod_datalynx#92]
The custom filter should be expanded like an accordeon:

- Add checkbox (default checked) to custom filter settings, that renders the custom filter within an accordeon:
- When activated the custom filter form is hidden and the custom filter form opens via a click on "Search" button
- Technique to use: https://getbootstrap.com/docs/4.0/components/collapse/

**Comment by michaelpollak** [comment]
As we already use an mform, why don't we introduce a header and make it default collapsed? I'll push this patch first, thanks for your feedback David.

![grafik](https://user-images.githubusercontent.com/475798/74748031-263f9900-5268-11ea-8e64-c6622a1b9315.png)

**Comment by dasistwas** [comment]
Thank you, great idea. One addition:
Instead of "Custom filter" please use:
get_string('search', 'search');
