### ISSUE TITLE
Check default views for validation

### ISSUE THREAD

**Issue by michaelpollak** [dasistwas/moodle-mod_datalynx#97]
Already created views have validation errors hardcoded in them. For example the tables with align="center". This throws a validation error, but can only be fixed if we go through and change all created views in the database. As this is a massive change I would not recommend, as stated above.

"Already created tables and problems: We do not touch that for the moment. We only work on the default templates so that upon creation of a new view, it will be validated."

**Comment by michaelpollak** [comment]
All views are checked and ok, validation errors are only from moodle core, see commit: 
https://github.com/michaelpollak/moodle-mod_datalynx/commit/273315946e9df1d7fa27daaeaba8944f78060e06

**Comment by dasistwas** [comment]
Perfect, thanks!
