### ISSUE TITLE
wrap virtual does not validate.

### ISSUE THREAD

**Issue by michaelpollak** [dasistwas/moodle-mod_datalynx#99]
For textareas we use 'wrap' => 'virtual', which throws validation errors. I've read that this attribute was used by IE and caused the text to wrap but no break lines were added to the output of the form.
Correction according to "the internet" is to use wrap = soft, see https://www.w3schools.com/tags/att_textarea_wrap.asp

**Comment by dasistwas** [comment]
Perfect, thank you! As soft is default, we could as well just omit it, but it is fine like that.
